[project]
name = "canteen"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "JohnRushKucharski", email = "johnkucharski@gmail.com" }
]
requires-python = ">=3.13"
dependencies = []

[project.optional-dependencies]
units = [
    "units",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "ipykernel>=6.29.5",
    "mypy>=1.17.1",
    "pytest>=8.4.2",
    "ruff>=0.12.12",
]

[tool.uv.sources]
units = { git = "https://github.com/JohnRushKucharski/units" }

[tool.pytest.ini_options]
testpaths = ["tests"]
python_files = ["test_*.py"]
python_classes = ["Test*"]
python_functions = ["test_*"]
addopts = ["-v", "--tb=short"]
